### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by Suburbanno** [patthekenny/LCUtils#2]

**Comment by ptkenny** [comment]
Good point. I’ll make a windows binary later today.

**Comment by Suburbanno** [comment]
waiting <3

**Comment by ptkenny** [comment]
Sorry, busy with real life stuff at the moment. I’ll make binaries as soon as I can.

**Comment by ptkenny** [comment]
Here you go, first release: https://github.com/patthekenny/LCUtils/releases/tag/v1.0

**Comment by Suburbanno** [comment]
thanks guys <3
