### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Suburbanno** [patthekenny/LCUtils#4]
by opening the LCUtils and selecting the League of Legends Directory, it is locked on a white screen and nothing happens.
![sdf](https://user-images.githubusercontent.com/13632826/34569298-7dd2a648-f14f-11e7-944b-74504c022f9e.PNG)

**Comment by ptkenny** [comment]
I tested so many times to make sure it would work, ugh. I'll fix it soon. I need to fire up a VM or something with node not touching it.

**Comment by Suburbanno** [comment]
ok, waiting

**Comment by ptkenny** [comment]
Can you put the logs from when you ran the program? (logs located in C:\Users\<USER>\AppData\Local\Programs\lcutils\resources\app\logs)

**Comment by Suburbanno** [comment]
wow, apparently it is working, I chose the folder "Riot Gamess" instead of "League of Legends" in the folder of "Riot Games" is also the folder of PBE.

**Comment by Suburbanno** [comment]
I will test the features now

**Comment by Suburbanno** [comment]
working
